use_frameworks!

platform :ios, '11.0'

target 'IdxDmpSdk_Example' do
  pod 'IdxDmpSdk', :path => '../'
  pod 'Google-Mobile-Ads-SDK'

  target 'IdxDmpSdk_Tests' do
    inherit! :search_paths

    
  end
end
